name: Events Demo 1
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
      - name: Run tests
        run: echo "Running tests..."
      - name: Output event data
        run: |
          echo "Event data: ${{ toJson(github.event) }}"

