name: Outputs and Artifacts Workflow 
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code 
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            
      - name: Install dependencies
        run: npm install 
        working-directory: artifacts-outputs
      - name: Run lint
        run: npm run lint
        working-directory: artifacts-outputs
      - name: Run tests
        run: npm test
        working-directory: artifacts-outputs
  build: 
    runs-on: ubuntu-latest
    needs: test
    outputs:
      asset_file: ${{ steps.output_asset.outputs.asset_file }}
    steps:
      - name: Get code 
        uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install 
        working-directory: artifacts-outputs
      - name: Build project
        run: npm run build
        working-directory: artifacts-outputs
      - name: Output JS File name
        id: output_asset
        run: |
          ASSET_FILE=$(ls artifacts-outputs/dist/assets/*.js)
          echo "Asset file name: $ASSET_FILE"
          echo "asset_file=$ASSET_FILE" >> $GITHUB_OUTPUT
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with: 
          name: dist-files
          path: |
           artifacts-outputs/dist
           artifacts-outputs/package.json 
    
  deploy: 
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files
      - name: Output build artifact contents
        run: |
          echo "Contents of dist-files artifact:"
          ls 
      - name: Output asset file from build job
        run: |
         echo "Asset file from build job: ${{ needs.build.outputs.asset_file }}"
      - name: Deploy to production
        run: echo "Deploying to production..."      